<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ngii_ntrip</name>
  <version>0.0.1</version>
  <description>NGII 실시간(VRS) NTRIP 클라이언트 (GGA 전송 지원) + F9P RTK 런치</description>
  <maintainer email="han@todo.todo">han</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>rtcm_msgs</exec_depend>
  <exec_depend>ublox_dgnss_node</exec_depend>
  <exec_depend>ublox_nav_sat_fix_hp_node</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
